### PR TITLE
MNT: Re-render the feedstock (Pt. 2)

### PR DESCRIPTION
**Pull request by jakirkham**
Absorbs this re-rendering PR ( https://github.com/conda-forge/hdf5-feedstock/pull/12 ) and merges it with `master` so that it includes this pinning PR ( https://github.com/conda-forge/hdf5-feedstock/pull/10 ).

### CODE REVIEW

**Comment by jakirkham** [comment]
So, this must be introduced in `conda-build` 1.20.2. This is a pretty serious problem as we use this everywhere now. Thoughts on this, @msarahan?

```
Error: Invalid selector in meta.yaml line 40:
    - python {{ environ['PY_VER'] + '*' }}  # [win]
```

**Comment by jakirkham** [comment]
Let's try downgrading `conda-build` to see if this problem goes away.

**Comment by jakirkham** [comment]
Yep, downgrading `conda-build` from 1.20.2 to 1.20.1 on CircleCI resolves the issue. That suggests this is, in fact, a regression.

**Comment by jakirkham** [comment]
Added to this `conda-build` issue ( https://github.com/conda/conda-build/issues/955 ). Going to hold off on this PR and the original re-rendering PR ( https://github.com/conda-forge/hdf5-feedstock/pull/12 ) for the near term.

**Comment by jakirkham** [comment]
Switching to selectors for the python test requirement.

**Comment by jakirkham** [comment]
Alright, this seems to work. Going to let it sit to get some feedback on whether the workaround here is acceptable or not.

**Comment by jakirkham** [comment]
There is a potential release of `conda-build on the horizon. So, am going to hold steady here. :horse:

**Comment by ocefpaf** [comment]
I don't think this is still needed.

**Comment by jakirkham** [comment]
Actually, it kind of is as we are still pinned to old versions of `conda-build`. Still I'm not eager to merge this as I'm hoping we can unpin these. When @pelson and I were talking about features, I asked him about freeing these pinnings. Basically we decided to hold a week as we might start doing this with a [package]( https://github.com/conda-forge/conda-forge-build-setup-feedstock ) that handles the pinnings for us orthogonal to what is done in the CI scripts. It should help cutdown redundant PRs like this and avoid these pinnings driving `conda-smithy` releases.

**Comment by jakirkham** [comment]
Ugh...I think I need to merge this. I know that CircleCI is failing without this change as I restarted the previous PR earlier. As I want to start making 1.8.15.x releases, we need to get this feedstock operational again. We can deal with this for the meantime.

**Pull request merged**
