### PR TITLE
Use MSYS2 patch to include szip support via libaec on Windows

### LINKED ISSUE #197: SZIP/libaec support on Windows
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

Refiling of https://github.com/conda-forge/h5py-feedstock/issues/63 to here

This is a known issue from https://github.com/conda-forge/hdf5-feedstock/pull/179#issuecomment-1207396346 and the residual of #120 .

I'm noting that MSYS2 has a patch that possibly addresses this issue.
https://github.com/msys2/MINGW-packages/blob/master/mingw-w64-hdf5/hdf5-fix-find-szip.patch
https://packages.msys2.org/base/mingw-w64-hdf5

Upstream appears to have fixed this issue.
https://github.com/HDFGroup/hdf5/pull/2492

### Installed packages

```shell
bzip2              conda-forge/win-64::bzip2-1.0.8-h8ffe710_4
  ca-certificates    conda-forge/win-64::ca-certificates-2022.12.7-h5b45459_0
  cached-property    conda-forge/noarch::cached-property-1.5.2-hd8ed1ab_1
  cached_property    conda-forge/noarch::cached_property-1.5.2-pyha770c72_1
  h5py               conda-forge/win-64::h5py-3.8.0-nompi_py311hfbc32a6_101
  hdf5               conda-forge/win-64::hdf5-1.14.0-nompi_h5af7005_102
  intel-openmp       conda-forge/win-64::intel-openmp-2023.0.0-h57928b3_25922
  krb5               conda-forge/win-64::krb5-1.20.1-heb0366b_0
  libblas            conda-forge/win-64::libblas-3.9.0-16_win64_mkl
  libcblas           conda-forge/win-64::libcblas-3.9.0-16_win64_mkl
  libcurl            conda-forge/win-64::libcurl-7.88.1-h68f0423_0
  libffi             conda-forge/win-64::libffi-3.4.2-h8ffe710_5
  libhwloc           conda-forge/win-64::libhwloc-2.9.0-h51c2c0f_0
  libiconv           conda-forge/win-64::libiconv-1.17-h8ffe710_0
  liblapack          conda-forge/win-64::liblapack-3.9.0-16_win64_mkl
  libsqlite          conda-forge/win-64::libsqlite-3.40.0-hcfcfb64_0
  libssh2            conda-forge/win-64::libssh2-1.10.0-h9a1e1f7_3
  libxml2            conda-forge/win-64::libxml2-2.10.3-hc3477c8_0
  libzlib            conda-forge/win-64::libzlib-1.2.13-hcfcfb64_4
  mkl                conda-forge/win-64::mkl-2022.1.0-h6a75c08_874
  numpy              conda-forge/win-64::numpy-1.24.2-py311h0b4df5a_0
  openssl            conda-forge/win-64::openssl-3.0.8-hcfcfb64_0
  pip                conda-forge/noarch::pip-23.0.1-pyhd8ed1ab_0
  pthreads-win32     conda-forge/win-64::pthreads-win32-2.9.1-hfa6e2cd_3
  python             conda-forge/win-64::python-3.11.0-hcf16a7b_0_cpython
  python_abi         conda-forge/win-64::python_abi-3.11-3_cp311
  setuptools         conda-forge/noarch::setuptools-67.5.1-pyhd8ed1ab_0
  tbb                conda-forge/win-64::tbb-2021.8.0-h91493d7_0
  tk                 conda-forge/win-64::tk-8.6.12-h8ffe710_0
  tzdata             conda-forge/noarch::tzdata-2022g-h191b570_0
  ucrt               conda-forge/win-64::ucrt-10.0.22621.0-h57928b3_0
  vc                 conda-forge/win-64::vc-14.3-hb6edc58_10
  vs2015_runtime     conda-forge/win-64::vs2015_runtime-14.34.31931-h4c5c07a_10
  wheel              conda-forge/noarch::wheel-0.38.4-pyhd8ed1ab_0
  xz                 conda-forge/win-64::xz-5.2.6-h8d14728_0
```

### Environment info

```shell
(h5py_hdf5_test) C:\>conda info

     active environment : h5py_hdf5_test
    active env location : C:\Users\_\.julia\conda\3\envs\h5py_hdf5_test
            shell level : 2
       user config file : C:\Users\_\.condarc
 populated config files :
          conda version : 4.10.3
    conda-build version : not installed
         python version : 3.9.5.final.0
       virtual packages : __cuda=11.7=0
                          __win=0=0
                          __archspec=1=x86_64
       base environment : C:\Users\_\.julia\conda\3  (writable)
      conda av data dir : C:\Users\_\.julia\conda\3\etc\conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Users\_\.julia\conda\3\pkgs
                          C:\Users\_\.conda\pkgs
                          C:\Users\_\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\_\.julia\conda\3\envs
                          C:\Users\_\.conda\envs
                          C:\Users\_\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.10.3 requests/2.25.1 CPython/3.9.5 Windows/10 Windows/10.0.19044
          administrator : False
             netrc file : None
           offline mode : False
```

### PR DESCRIPTION
**Pull request by mkitti**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Fix #197 using patch from MSYS2.

### CODE REVIEW

**Comment by mkitti** [comment]
@conda-forge-admin, please rerender

**Comment by mkitti** [comment]
@conda-forge-admin, please restart ci

**Comment by mkitti** [comment]
@conda-forge-admin, please rerender

**Comment by mkitti** [comment]
An alternative patch, closer to upstream may look like this:

```diff
--- CMakeFilters.cmake.org      2023-03-07 21:25:34.573028100 -0500
+++ CMakeFilters.cmake  2023-03-07 21:38:45.713588200 -0500
@@ -59,18 +59,16 @@
       find_package (ZLIB NAMES ${ZLIB_PACKAGE_NAME}${HDF_PACKAGE_EXT} COMPONENTS static shared)
       if (NOT ZLIB_FOUND)
         find_package (ZLIB) # Legacy find
-        if (ZLIB_FOUND)
-          set (LINK_COMP_LIBS ${LINK_COMP_LIBS} ${ZLIB_LIBRARIES})
-        endif ()
       endif ()
-    endif ()
-    if (ZLIB_FOUND)
-      set (H5_HAVE_FILTER_DEFLATE 1)
-      set (H5_HAVE_ZLIB_H 1)
-      set (H5_HAVE_LIBZ 1)
-      set (H5_ZLIB_HEADER "zlib.h")
-      set (ZLIB_INCLUDE_DIR_GEN ${ZLIB_INCLUDE_DIR})
-      set (ZLIB_INCLUDE_DIRS ${ZLIB_INCLUDE_DIRS} ${ZLIB_INCLUDE_DIR})
+      if (ZLIB_FOUND)
+        set (H5_HAVE_FILTER_DEFLATE 1)
+        set (H5_HAVE_ZLIB_H 1)
+        set (H5_HAVE_LIBZ 1)
+        set (H5_ZLIB_HEADER "zlib.h")
+        set (ZLIB_INCLUDE_DIR_GEN ${ZLIB_INCLUDE_DIR})
+        set (ZLIB_INCLUDE_DIRS ${ZLIB_INCLUDE_DIRS} ${ZLIB_INCLUDE_DIR})
+        set (LINK_COMP_LIBS ${LINK_COMP_LIBS} ${ZLIB_LIBRARIES})
+      endif ()
     else ()
       if (HDF5_ALLOW_EXTERNAL_SUPPORT MATCHES "GIT" OR HDF5_ALLOW_EXTERNAL_SUPPORT MATCHES "TGZ")
         EXTERNAL_ZLIB_LIBRARY (${HDF5_ALLOW_EXTERNAL_SUPPORT})
@@ -116,18 +114,16 @@
       find_package (SZIP NAMES ${SZIP_PACKAGE_NAME}${HDF_PACKAGE_EXT} COMPONENTS static shared)
       if (NOT SZIP_FOUND)
         find_package (SZIP) # Legacy find
-        if (SZIP_FOUND)
-          set (LINK_COMP_LIBS ${LINK_COMP_LIBS} ${SZIP_LIBRARIES})
-        endif ()
+      endif ()
+      if (SZIP_FOUND)
+        set (H5_HAVE_FILTER_SZIP 1)
+        set (H5_HAVE_SZLIB_H 1)
+        set (H5_HAVE_LIBSZ 1)
+        set (SZIP_INCLUDE_DIR_GEN ${SZIP_INCLUDE_DIR})
+        set (SZIP_INCLUDE_DIRS ${SZIP_INCLUDE_DIRS} ${SZIP_INCLUDE_DIR})
+        set (LINK_COMP_LIBS ${LINK_COMP_LIBS} ${SZIP_LIBRARIES})
       endif ()
     endif ()
-  endif ()
-  if (SZIP_FOUND)
-    set (H5_HAVE_FILTER_SZIP 1)
-    set (H5_HAVE_SZLIB_H 1)
-    set (H5_HAVE_LIBSZ 1)
-    set (SZIP_INCLUDE_DIR_GEN ${SZIP_INCLUDE_DIR})
-    set (SZIP_INCLUDE_DIRS ${SZIP_INCLUDE_DIRS} ${SZIP_INCLUDE_DIR})
   else ()
     if (HDF5_ALLOW_EXTERNAL_SUPPORT MATCHES "GIT" OR HDF5_ALLOW_EXTERNAL_SUPPORT MATCHES "TGZ")
       EXTERNAL_SZIP_LIBRARY (${HDF5_ALLOW_EXTERNAL_SUPPORT} ${HDF5_ENABLE_SZIP_ENCODING})
```

**Comment by mkitti** [comment]
This looks promising.

```
Found SZIP: D:/bld/hdf5_1678243983890/_h_env/Library/lib/szip.lib  
```

**Comment by mkitti** [comment]
Yes, I think we have it.

```
2023-03-08T03:02:35.2302704Z    INFO (hdf5,Library/bin/hdf5.dll): Needed DSO Library/bin/szip.dll found in conda-forge::libaec-1.0.6-h63175ca_1
```

**Comment by mkitti** [comment]
Cool, it built. Putting the other platforms back in and rerendering.

**Comment by mkitti** [comment]
@conda-forge-admin, please rerender

**Comment by mkitti** [comment]
Let me know if there is anything else to do. Thanks.

**Comment by ocefpaf** [comment]
LGTM! Thanks!! Should we upstream that patch?

**Comment by mkitti** [comment]
Upstream has https://github.com/HDFGroup/hdf5/pull/2492 which is much more involved.

**Comment by jakirkham** [comment]
Thanks Mark and Filipe! 🙏

**Comment by dwr-psandhu** [comment]
@mkitti Is this available on conda-forge for windows ? I built an environment with conda-forge and the dependencies for libaec (1.0.6) are installed along with h5py (3.9.0) and hdf5 (1.14.1). However the test referenced above fails ?

```Python 3.11.4 | packaged by conda-forge | (main, Jun 10 2023, 17:59:51) [MSC v.1935 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import h5py
>>> with h5py.File("test.h5", "w") as h5f:
...   ds = h5f.create_dataset("test", (1024, 1024), chunks=(16,16), dtype="uint16", compression="szip", compression_opts=('ec',32))
...
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "c:\Users\psandhu\Miniconda3\envs\pydsm\Lib\site-packages\h5py\_hl\group.py", line 183, in create_dataset
    dsid = dataset.make_new_dset(group, shape, dtype, data, name, **kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\psandhu\Miniconda3\envs\pydsm\Lib\site-packages\h5py\_hl\dataset.py", line 104, in make_new_dset
    dcpl = filters.fill_dcpl(
           ^^^^^^^^^^^^^^^^^^
  File "c:\Users\psandhu\Miniconda3\envs\pydsm\Lib\site-packages\h5py\_hl\filters.py", line 186, in fill_dcpl
    raise ValueError('Compression filter "%s" is unavailable' % compression)
ValueError: Compression filter "szip" is unavailable
>>>```

**Comment by mkitti** [comment]
I think something may have changed with 1.14.1. Could you check 1.14.0?

**Comment by dwr-psandhu** [comment]
I think it has. It works if hdf5 is pinned to 1.14.0 !
Perhaps an upstream fix for using libaec is available now and this patch is interfering ?

**Comment by mkitti** [comment]
Could you create a new issue to track this here? It is an issue for the feedstock.

I believe some changes were made upstream by HDF Group which means the configuration here may no longer work. I also recently noticed this in the Julia and MSYS2 builds as well.

I'm actually at the HDF5 User Group meeting at the moment, so I will investigate. Please tag me on the new issue.

**Pull request merged**
