### PR TITLE
Correct maintainer info

### PR DESCRIPTION
**Pull request by groutr**

### CODE REVIEW

**Comment by ocefpaf** [comment]
No need to wait for the CIs. Thanks @groutr!

**Comment by jakirkham** [comment]
I was going to ask that we re-render as we are going to get build failures otherwise.

**Comment by ocefpaf** [comment]
The build number was not bumped, so no new build is needed.

**Comment by jakirkham** [comment]
Right, but we are going to have CI failures.

**Comment by jakirkham** [comment]
@groutr, did you ever get an invite to join conda-forge in your email?

**Comment by jakirkham** [comment]
Ping @groutr.

**Pull request merged**
