### PR TITLE
Remove COPYING File from Library to avoid clobber warning.

### PR DESCRIPTION
**Pull request by hmaarrfk**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by hmaarrfk** [comment]
@conda-forge-admin please rerender

**Comment by hmaarrfk** [comment]
I would appreciate this being merged  even if OSX/Linux fail since this is a windows only fix.

I expect linux to fail due to https://github.com/conda-forge/docker-images/issues/165

**Comment by hmaarrfk** [comment]
@beckermr i'm going to go ahead and remove a few other generic sounding files.


```
-- Installing: D:/bld/hdf5_split_1606931441906/_h_env/Library/./COPYING
-- Installing: D:/bld/hdf5_split_1606931441906/_h_env/Library/./USING_HDF5_CMake.txt
-- Up-to-date: D:/bld/hdf5_split_1606931441906/_h_env/Library/./COPYING
-- Installing: D:/bld/hdf5_split_1606931441906/_h_env/Library/./RELEASE.txt
-- Installing: D:/bld/hdf5_split_1606931441906/_h_env/Library/./USING_HDF5_VS.txt
```

**Comment by scopatz** [comment]
Maybe it would be better to patch out that part of the CMake file rather than removing it after install?

**Comment by hmaarrfk** [comment]
crossplatform patching is really annoying....

can you maybe also comment on: https://github.com/conda-forge/hdf5-feedstock/issues/87#issuecomment-737445475

**Comment by beckermr** [comment]
Installing and then removing is more robust than patching the build. It won't ever go out of date as the build changes. The worst-case scenario is that we miss a file to remove and have to come back and fix it later. Updating patches is an awful job. 

LGTM!

**Comment by beckermr** [comment]
Woops. That was the bot that merged since we forgot to remove the automerge label. We can back this out if others have more comments.

**Comment by hmaarrfk** [comment]
Yeah, lets discuss in: https://github.com/conda-forge/hdf5-feedstock/issues/87#issuecomment-737445475

I think i found a good variable to update.

**Pull request merged**
