### PR TITLE
Update 1.12.2

### PR DESCRIPTION
**Pull request by hmaarrfk**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by hmaarrfk** [comment]
Does anybody want to enable the new build options?
https://support.hdfgroup.org/ftp/HDF5/releases/hdf5-1.12/hdf5-1.12.2/src/hdf5-1.12.2-RELEASE.txt

**Comment by matham** [comment]
There has been some changes to cross-compiling (https://github.com/h5py/h5py/pull/2087#issuecomment-1116513533). So some of the mac patches would need to be dropped or updated. 

That issue was kinda my motivation for mentioning it as I copied the current feedstock patches when I added support for apple silicon in that repo 😁

**Comment by hmaarrfk** [comment]
got it. Yeah, i might not have time to refresh it so much. You can make the PR to help! I'm hoping it is just deleting patches.

**Comment by matham** [comment]
[Here's the patch](https://github.com/h5py/h5py/blob/3a0dde67eca2d398d3a33fe2bd1272fe8000b8ae/ci/osx_cross_configure.patch) if you want to include it. It just needed to be updated without much changes.

**Comment by hmaarrfk** [comment]
Thanks lets try it.

I somewhat prefer patching everything when it comes to build scripts, it helps keep things consistent.

**Comment by matham** [comment]
I don't think a lot changed in terms of the patches for the new version so I don't think we can drop it just yes. Ohh I guess I only regenerated the patches that I used. I'll see what's up with the other patches, if you don't get to it first.

**Comment by visr** [comment]
Thanks for working on this. What is the status of this? It seems the build logs are gone.

Since HDF5 cross compilation is not fully supported yet, the Julia community redistributes the conda-forge builds on some platforms ([see build script](https://github.com/JuliaPackaging/Yggdrasil/blob/f064fe369375526458eb67e07b969c1155d8ed55/H/HDF5/build_tarballs.jl)). Unfortunately 1.12.1 saw some regressions that seem fixed in 1.12.2, regarding libnetcdf/libhdf5 interop.

**Comment by hmaarrfk** [comment]
@conda-forge-admin please rerender

**Comment by hmaarrfk** [comment]
> What is the status of this

It's stuck.

You can open a PR to help out.

Otherwise, there isn't really an ETA.

**Pull request merged**
