### PR TITLE
Change maintainer from @astrofrog to @astrofrog-conda-forge

### PR DESCRIPTION
**Pull request by astrofrog**
Hi there :wave:. This is an automated pull request to change the maintainer from @astrofrog to @astrofrog-conda-forge (having conda-forge as one of my organization makes the Travis and AppVeyor GitHub integrations extremely slow, so I've decided to have a dedicated account for conda-forge-related work)

### CODE REVIEW

**Comment by jakirkham** [comment]
So what I and another user did was just create an org and move/refork all our feedstocks in that org. That helped the CIs respond much faster.

**Comment by astrofrog** [comment]
@jakirkham - does this require a lot of work in terms of getting the linter to work and getting new tokens for each CI? Does this mean opting out of auto-updates from the maintenance bot?

**Comment by jakirkham** [comment]
Should be clear "move" meant move existing forked feedstocks under my user to an org. Initially I moved a couple and decided it was easier (at least for me) to fork them again under the new org and delete the forks under my own user. Mainly because there was a GitHub API for the latter. :) Since they are just forks of the feedstocks, they are no different from any other forks. Take a look at the [org here]( https://github.com/jakirkham-feedstocks/ ) for an example.

**Comment by astrofrog** [comment]
@jakirkham - ah I see. The forks aren't really an issue for me, what was more of an issue was that when adding projects to appveyor or travis, it shows repositories for all organizations I'm part of, including all the conda-forge repositories.

**Comment by astrofrog** [comment]
Would it be ok to merge this?

**Comment by jakirkham** [comment]
Done. Sorry, think I lost track of this one.

**Pull request merged**
