### PR TITLE
Enable Fortran 2003

### PR DESCRIPTION
**Pull request by scopatz**
This is needed for some downstream packages for HDF5 < 1.10. https://github.com/mit-crpg/openmc/issues/727#issuecomment-250870760

### CODE REVIEW

**Comment by scopatz** [comment]
Ok @astrofrog, I have added a test and it seems to work, but the appveyor queue is taking a long time. Also note the f2003 test has an f90 extension.  This was the original extension that the HDF5 group provides.

**Comment by ocefpaf** [comment]
> but the appveyor queue is taking a long time. 

There is no need to wait on AppVeyor here b/c there BTW. If @astrofrog is OK with this change feel free to merge. I am :+1: to this.

**Comment by scopatz** [comment]
Looks like Windows now passes too.

**Comment by scopatz** [comment]
Can thos please be looked at again. It is blocking development of other recipes...

**Comment by scopatz** [comment]
Thanks!

**Pull request merged**
