### PR TITLE
Rerender

### PR DESCRIPTION
**Pull request by ocefpaf**
Re-render and change the `skip` section b/c of https://travis-ci.org/conda-forge/hdf5-feedstock/builds/216313181#L251

### CODE REVIEW

**Comment by ocefpaf** [comment]
@astrofrog it seems that the `Fortran` tests are broken. Can you take a look?

**Comment by astrofrog** [comment]
I don't have time to look into this in the next week or so unfortunately. Has there been an HDF5 version change?

**Comment by jakirkham** [comment]
It seems the answer is HDF5 shared libraries don't work correctly on Mac when Fortran is enabled and that this is likely a compiler issue. Please see PR ( https://github.com/conda-forge/hdf5-feedstock/pull/69 ) for a potential fix and related discussion.

**Comment by jakirkham** [comment]
Resolve by PR ( https://github.com/conda-forge/hdf5-feedstock/pull/69 ).

**Pull request closed without merging**
