### PR TITLE
Test: Add Fortran bindings

### PR DESCRIPTION
**Pull request by jakirkham**
This absorbs PR ( https://github.com/conda-forge/hdf5-feedstock/pull/28 ) from @astrofrog to test Fortran support. This will deploy to the `test` label when merged. The only changes presented in this PR that are not in PR ( https://github.com/conda-forge/hdf5-feedstock/pull/28 ) are changes to the configuration of where this is deployed. Thus we should be able to try this package out for some time. Once we are comfortable with it, we can release it formally.

### CODE REVIEW

**Comment by jakirkham** [comment]
Letting you know about this, @pelson. Basically am trying to explore a release process with @astrofrog so that we can take smaller steps with big changes. This should allow us to release something into the open under the `test` label that we may not be comfortable releasing into `main` quite yet. Thus if we find there are serious issues, it does not cause so much of a ruckus. Though @astrofrog shared some [better ideas]( https://github.com/conda-forge/hdf5-feedstock/pull/28#issuecomment-238109232 ) for letting this scale, which seem worthy of discussion.

**Comment by astrofrog** [comment]
:+1:

**Comment by jakirkham** [comment]
So I'm thinking maybe we should break out the test configuration as one PR ( https://github.com/conda-forge/hdf5-feedstock/pull/32 ) to create the `test` branch. It might be nice to adjust it a bit more and I think I can use the feedback. Not aiming to solve issue ( https://github.com/conda-forge/conda-forge.github.io/issues/204 ), but at least provide something to hold us over in the meantime.

**Comment by astrofrog** [comment]
@jakirkham - can we go ahead and merge this and #32? (then I'll start doing some tests to see if everything works fine to build other packages that depend on this)

**Comment by jakirkham** [comment]
Yep, going to do exactly that. Sorry I held it off for so long. Was hoping to engage others in a discussion about this, but it seems maybe the best way is just to try it out.

**Comment by jakirkham** [comment]
So this should be in the `test` channel soon.

**Comment by astrofrog** [comment]
Thanks!

**Comment by jakirkham** [comment]
Of course. Sorry it took so long. 😞

It does appear they are all deployed now, so please let me know how it goes. I'll try to take a look later next week if not sooner.

**Pull request merged**
