### PR TITLE
HDF5: 1.14.4.3 (help wanted)

### LINKED ISSUE #228: HDF5 1.14.4
Can we ship a release for 1.14.3? :)

I am tripping in CI over https://github.com/HDFGroup/hdf5/issues/3831, which is fixed in the latest release :)

### PR DESCRIPTION
**Pull request by ax3l**
The latest bugfix release of HDF5 1.14

Close #228

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by ax3l** [comment]
I probably will need help to redo these patches :pray:

**Comment by hmaarrfk** [comment]
clone both repos locally, then checkout the version 1.14.4.3, then 

```
git am
```
or
```
git apply
```
can help!

Let me know if you need more guidance!

**Comment by ax3l** [comment]
Thanks, I mean the patches for the configure logic.

I have to admit, I did not see the heavy patching for get HDF5 built with autotools. I will probably not have time for this in the coming two weeks (and I have barely any autotools experience). If someone wants to take over, please feel free to push here or close this PR.

**Comment by ax3l** [comment]
Thank you so much @zklaus! closing in favor of #231 :)

**Pull request closed without merging**
