### PR TITLE
MNT: rerender

### LINKED ISSUE #173: @conda-forge-admin please rerender
### Additional comment:

_No response_

### PR DESCRIPTION
**Pull request by conda-forge-linter**
Hi! This is the friendly automated conda-forge-webservice.

I've rerendered the recipe as instructed in #173.

Here's a checklist to do before merging.
- [ ] Bump the build number if needed.

Fixes #173

### CODE REVIEW

**Comment by hmaarrfk** [comment]
@conda-forge-admin please rerender

**Comment by matham** [comment]
There's a new HDF5 release FYI.

**Comment by hmaarrfk** [comment]
Which one?

**Comment by matham** [comment]
[1.12.2](https://github.com/HDFGroup/hdf5/releases/tag/hdf5-1_12_2).

**Comment by hmaarrfk** [comment]
Thanks for the note. https://github.com/conda-forge/hdf5-feedstock/pull/175

**Pull request closed without merging**
