### PR TITLE
update patch for 1.12.2

### PR DESCRIPTION
**Pull request by visr**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

This updates the patch that could not be applied in #175.

### CODE REVIEW

**Comment by visr** [comment]
It looks like OSX fails, but only on ARM64 with MPI (`nompi` passes). These all fail with the same error during testing of the parallel `h5perf`:

```
============================
Test log for h5perf 
============================
./h5perf: line 117: /Users/runner/miniforge3/conda-bld/hdf5_split_1658899880313/work/tools/src/h5perf/.libs/h5perf: Bad CPU type in executable
./h5perf: line 117: /Users/runner/miniforge3/conda-bld/hdf5_split_1658899880313/work/tools/src/h5perf/.libs/h5perf: Undefined error: 0
./h5perf: line 117: /Users/runner/miniforge3/conda-bld/hdf5_split_1658899880313/work/tools/src/h5perf/.libs/h5perf: Bad CPU type in executable
./h5perf: line 117: /Users/runner/miniforge3/conda-bld/hdf5_split_1658899880313/work/tools/src/h5perf/.libs/h5perf: Undefined error: 0
        0.41 real         0.02 user         0.04 sys
make[6]: *** [Makefile:1442: h5perf.chkexe_] Error 1
make[6]: Leaving directory '/Users/runner/miniforge3/conda-bld/hdf5_split_1658899880313/work/tools/src/h5perf'
make[5]: *** [Makefile:1568: build-check-p] Error 1
make[5]: Leaving directory '/Users/runner/miniforge3/conda-bld/hdf5_split_1658899880313/work/tools/src/h5perf'
make[4]: *** [Makefile:1423: test] Error 2
make[4]: Leaving directory '/Users/runner/miniforge3/conda-bld/hdf5_split_1658899880313/work/tools/src/h5perf'
make[3]: *** [Makefile:1220: check-am] Error 2
make[3]: Leaving directory '/Users/runner/miniforge3/conda-bld/hdf5_split_1658899880313/work/tools/src/h5perf'
make[2]: *** [Makefile:874: check-recursive] Error 1
make[2]: Leaving directory '/Users/runner/miniforge3/conda-bld/hdf5_split_1658899880313/work/tools/src'
make[1]: *** [Makefile:880: check-recursive] Error 1
make[1]: Leaving directory '/Users/runner/miniforge3/conda-bld/hdf5_split_1658899880313/work/tools'
make: *** [Makefile:723: check-recursive] Error 1
```

As can be seen here: https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=541906&view=logs&j=c35410bf-a820-56fd-e231-d3cd4bead63c&t=b92b255f-9dfe-5c14-4730-460f7a671001&l=5576

I'm not sure what to do. `h5perf_serial` received attention previously in #2, #148 and #149, so now if I understand correctly `h5perf_serial` doesn't have to be present when cross compiling.

https://github.com/conda-forge/hdf5-feedstock/blob/cbbd57d58f7f5350ca679eaad49354c11dd32b95/recipe/meta.yaml#L149-L152

**Comment by hmaarrfk** [comment]
I think the tests sections get skipped on osx arm always.

Can you skip in bash the line in the install.sh file 

```

  make check RUNPARALLEL="${RECIPE_DIR}/mpiexec.sh -n 2"

**Comment by hmaarrfk** [comment]
For education:

I think the correct thing to do is to use a variable dedicated to the detection of cross compilation:

https://github.com/conda-forge/hdf5-feedstock/blob/cbbd57d58f7f5350ca679eaad49354c11dd32b95/recipe/build.sh#L53

But it gets tiring keeping up with everything

**Comment by hmaarrfk** [comment]
tou want to test for cross compilation, and lack of emulation capabilities. i donr know if we havd a variable for the later.

**Comment by hmaarrfk** [comment]
@conda-forge-admin please rerender

**Comment by hmaarrfk** [comment]
Thank you!

**Comment by hmaarrfk** [comment]
we can't cross compile on linux because the build script isn't set up it seems.

**Comment by hmaarrfk** [comment]
so time to just wait 2 hours.

**Pull request merged**
