### PR TITLE
Arch: Add ppc64le

### PR DESCRIPTION
**Pull request by ax3l**
Add builds for this new platform.
Requires an explicit dependency on `make`.

Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by ax3l** [comment]
@conda-forge-admin, please rerender

**Comment by ax3l** [comment]
git@github.com:conda-forge/hdf5-feedstock.git

**Comment by ax3l** [comment]
@conda-forge-admin, please rerender

**Comment by beckermr** [comment]
Travis failed due to the log length being too long. :/

**Comment by beckermr** [comment]
Now the build seems too quiet. There is a key we can add to the conda-forge.yaml to make travis wait longer or somthing.

**Comment by beckermr** [comment]
@conda-forge-admin, please rerender

**Comment by ax3l** [comment]
@beckermr can you try to restart the one last failed/timeout aarch64 build?

**Comment by beckermr** [comment]
We need to figure out if we can increase the build time. Even if it passes this time, the timeout makes the build unreliable.

**Comment by ax3l** [comment]
Yep, the aarch64 emulated builds are really slow. On the upside, the ppc builds on native hardware with travis finish even faster than the regular x86 builds :D

**Comment by beckermr** [comment]
Lol yes. I meant bump up the time limit for azure. Not much we can do about the slow emulation.

**Comment by beckermr** [comment]
Ahhhhh! I think we can set this

https://github.com/conda-forge/conda-smithy/blob/507e638913454d32d5c8f3c9c9823555f6c42b05/conda_smithy/configure_feedstock.py#L1231

**Comment by beckermr** [comment]
@conda-forge-admin, please rerender

**Comment by beckermr** [comment]
@conda-forge-admin, please rerender

**Comment by beckermr** [comment]
OK. The builds now have 10 hours to finish.

**Comment by ax3l** [comment]
oh dang :face_with_head_bandage: 
If you like, I am also ok to enable `ppc64le` first and we move in `aarch64` later, if any faster solution for CI arises for it.

**Comment by beckermr** [comment]
Seems like we have to do that. :/

**Comment by ax3l** [comment]
@conda-forge-admin, please rerender

**Comment by beckermr** [comment]
@ax3l I am looking at the aarch64 builds and it appears that what is taking so long are the tests. Can we not run a subset of those for the build?

**Comment by ax3l** [comment]
oh sure, fine for me as well.

**Comment by beckermr** [comment]
Also, it looks like azure killed the build after 5 hours and 59 min anyways which is annoying and not what I expected. I cannot tell if I am looking at the right one though.

**Comment by ax3l** [comment]
yes, saw that behaviour as well.

**Comment by beckermr** [comment]
@conda-forge/conda-smithy Do you all understand why increasing the timeout time for the azure builds did not work here? 

I set

```
azure:
  timeout_minutes: 600
```

in the `conda-build.yml`.

**Comment by beckermr** [comment]
It looks like we are skipping tests on ppc64le as well, so NBD.

**Comment by beckermr** [comment]
@conda-forge-admin, please rerender

**Comment by beckermr** [comment]
huzzah!

**Comment by beckermr** [comment]
Should I merge @ax3l ?

**Comment by isuruf** [comment]
Maximum we get is 360 minutes on azure.

Btw, if you care about aarch64, please look into https://github.com/conda-forge/conda-smithy/issues/1079. People send so much time in adding hacks to get builds passing in the time frame or fixing issues related to QEMU, which would go away if we used drone.

**Comment by beckermr** [comment]
Ahhhhhh Ok @isuruf. And yes, you told me about this earlier! Thanks!

**Pull request merged**
