### PR TITLE
1.10.11

### PR DESCRIPTION
**Pull request by nicogodet**
Checklist
* [X] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [X] Reset the build number to `0` (if the version changed)
* [X] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [X] Ensured the license file is being packaged.

To build `libmed`, fortran is required and version need to be <1.11.
I build locally with https://github.com/nicogodet/hdf5-otm-feedstock and https://github.com/nicogodet/med-otm-feedstock successfully.

Existing branch 1.10.x is old.
Currently targeting main to test build

### CODE REVIEW

**Comment by hmaarrfk** [comment]
is there an issue with newer HDF5? could we instead update linked, it looks quite crusty...

**Comment by nicogodet** [comment]
AFAIK libmed can not be built against hdf5 >1.10.x.
That's why I'm trying to have a proper 1.10.x version of hdf5

**Comment by nicogodet** [comment]
Even debian version https://packages.debian.org/fr/source/sid/med-fichier rely on hdf5 1.10.10 https://packages.debian.org/fr/sid/libhdf5-mpi-dev

**Comment by hmaarrfk** [comment]
Debian packages are generally much older.

med's website lists a version 9.11.0 

why not try building that?

Fail up, not down

**Comment by nicogodet** [comment]
Could you link this version ?

Because salome platform only list 5.0.0 (which is bugged) and 4.1.1
image
https://www.salome-platform.org/?page_id=2430

There is this trick https://gist.github.com/jedbrown/527ef81ff59a0dccf833da40fdd15a47
re-used by Alpine https://git.alpinelinux.org/aports/commit/?id=ffdc55847d28a26e20f4f3d0eb0d74e396c4e744
Worth a try...

**Comment by hmaarrfk** [comment]
on the git page 

https://git.salome-platform.org/gitweb/?p=modules/med.git;a=summary

**Comment by nicogodet** [comment]
This is the [SALOME Med module](https://git.salome-platform.org/gitweb/?p=modules/med.git;a=summary) not med-fichier/medfile/libmed itself.

**Comment by nicogodet** [comment]
And consider 1.10.x received its latest release last month.
https://support.hdfgroup.org/ftp/HDF5/releases/hdf5-1.10/hdf5-1.10.11/src/hdf5-1.10.11-RELEASE.txt

**Comment by hmaarrfk** [comment]
Feel free to make a PR to the `1.10.x` branch. I or some other developer listed as a maintainer here will happily review it.

Please try to start from the `1.10.x` branch to help minimize the changes to help us better review things.

Please consider that by using the `1.10.X` branch, you are effectively going to be pretty incompatible with the rest of the conda-forge ecosystem as it is today.  You will likely have to rebuild every package that uses HDF5, and there are many


To get a sense of how widespread the usage of HDF5 is, have a look at
https://conda-forge.org/status/#hdf51142

This lists the 98 packages that have been updated to use 1.14.2. If you use any of them, you will likely have to rebuild them to get them to work on 1.10.X. 

While it is all possible, really consider the difference of working to update your one package, instead of working to update a subset of the 98 packages you need.

I've spent alot of time getting HDF5 updated, generally speaking, HDF5 has strong backward compatibility in the code. You can often use C preprocessor definitions to choose which "version" of a function call you want to use. Very rarely was it "impossible" for me to "update" a package to use a more modern HDF5 version. The HDF5 developers are quite responsive as well should you have any final questions.

**Comment by nicogodet** [comment]
I'm currently trying to build hdf5 with `-DDEFAULT_API_VERSION:STRING=v110` and med with `-DH5_USE_110_API:BOOL=ON` as specified in hdf5 doc.
Build seems successful, need to test opentelemac-mascaret with it.

Could you consider building an hdf5 package with `-DDEFAULT_API_VERSION:STRING=v110` ?
Fortran support has a pending PR

**Comment by hmaarrfk** [comment]
> Could you consider building an hdf5 package with -DDEFAULT_API_VERSION:STRING=v110 ?

Can you not use `DH5_USE_110_API` without changing the default version?

**Comment by hmaarrfk** [comment]
please see:
https://github.com/conda-forge/libmed-feedstock/pull/50

**Pull request closed without merging**
